/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        manutencao = new javax.swing.JMenu();
        autor = new javax.swing.JMenuItem();
        categoriaProd = new javax.swing.JMenuItem();
        cidade = new javax.swing.JMenuItem();
        produtora = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cliente = new javax.swing.JMenuItem();
        filme = new javax.swing.JMenuItem();
        produto = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        pacotes = new javax.swing.JMenuItem();
        ajuda = new javax.swing.JMenu();
        sobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Cadastros");
        setMaximumSize(new java.awt.Dimension(1200, 700));
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/film.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/popcorn.png"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(1200, 60));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(1200, 60));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(1200, 60));

        manutencao.setText("Manutenção");
        manutencao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        manutencao.setMaximumSize(new java.awt.Dimension(120, 25));
        manutencao.setMinimumSize(new java.awt.Dimension(120, 25));
        manutencao.setPreferredSize(new java.awt.Dimension(120, 25));

        autor.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        autor.setText("Autor");
        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });
        manutencao.add(autor);

        categoriaProd.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        categoriaProd.setText("Categoria de Produtos");
        categoriaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaProdActionPerformed(evt);
            }
        });
        manutencao.add(categoriaProd);

        cidade.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cidade.setText("Cidade");
        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });
        manutencao.add(cidade);

        produtora.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        produtora.setText("Produtora");
        produtora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoraActionPerformed(evt);
            }
        });
        manutencao.add(produtora);
        manutencao.add(jSeparator1);

        cliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        manutencao.add(cliente);

        filme.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        filme.setText("Filme");
        filme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmeActionPerformed(evt);
            }
        });
        manutencao.add(filme);

        produto.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        produto.setText("Produto");
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });
        manutencao.add(produto);

        jMenuBar1.add(manutencao);

        jMenu1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu1.setLabel("Lançamentos    ");

        pacotes.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        pacotes.setText("Pacotes");
        pacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacotesActionPerformed(evt);
            }
        });
        jMenu1.add(pacotes);

        jMenuBar1.add(jMenu1);

        ajuda.setText("Ajuda    ");
        ajuda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        sobre.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        sobre.setText("Sobre");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });
        ajuda.add(sobre);

        jMenuBar1.add(ajuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(785, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(43, 43, 43))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        FormAutor autor = new FormAutor(this, true);
        autor.setTitle("Cadastro de Autores");
        autor.setLocationRelativeTo(null);
        autor.setVisible(true);
    }//GEN-LAST:event_autorActionPerformed

    private void categoriaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaProdActionPerformed
        FormCategProduto categProd = new FormCategProduto(this, true);
        categProd.setTitle("Cadastro de Categoria de Produtos");
        categProd.setLocationRelativeTo(null);
        categProd.setVisible(true);
    }//GEN-LAST:event_categoriaProdActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        FormCidade cidade = new FormCidade(this, true);
        cidade.setTitle("Cadastro de Cidades");
        cidade.setLocationRelativeTo(null);
        cidade.setVisible(true);
    }//GEN-LAST:event_cidadeActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        FormCliente cliente = new FormCliente(this, true);
        cliente.setTitle("Cadastro de Clientes");
        cliente.setLocationRelativeTo(null);
        cliente.setVisible(true);
    }//GEN-LAST:event_clienteActionPerformed

    private void filmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmeActionPerformed
        FormFilme filme = new FormFilme(this, true);
        filme.setTitle("Cadastro de Filmes");
        filme.setLocationRelativeTo(null);
        filme.setVisible(true);
    }//GEN-LAST:event_filmeActionPerformed

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        FormProduto produto = new FormProduto(this, true);
        produto.setTitle("Cadastro de Produtos");
        produto.setLocationRelativeTo(null);
        produto.setVisible(true);
    }//GEN-LAST:event_produtoActionPerformed

    private void produtoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoraActionPerformed
        FormProdutora produtora = new FormProdutora(this, true);
        produtora.setTitle("Cadastro de Produtoras");
        produtora.setLocationRelativeTo(null);
        produtora.setVisible(true);
    }//GEN-LAST:event_produtoraActionPerformed

    private void pacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacotesActionPerformed
        FormPacote pacote = new FormPacote(this, true);
        pacote.setTitle("Cadastro de Pacotes");
        pacote.setLocationRelativeTo(null);
        pacote.setVisible(true);
    }//GEN-LAST:event_pacotesActionPerformed

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed
        JOptionPane.showMessageDialog(null,"\nSistema de Cadastros\n\n" + "Para entrar em contato com o suporte ligue para 0800-808080");
    }//GEN-LAST:event_sobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajuda;
    private javax.swing.JMenuItem autor;
    private javax.swing.JMenuItem categoriaProd;
    private javax.swing.JMenuItem cidade;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JMenuItem filme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu manutencao;
    private javax.swing.JMenuItem pacotes;
    private javax.swing.JMenuItem produto;
    private javax.swing.JMenuItem produtora;
    private javax.swing.JMenuItem sobre;
    // End of variables declaration//GEN-END:variables
}
